sudo: true
language: go

go:
  - 1.5
  - 1.6
  - tip

install:
  - sudo apt-get update -y
  - sudo apt-get install -y libpcap-dev
  - go get -v ./server/jam-server

before_script:
  - chmod +x ./server/log-interceptor/test.sh
  - ifconfig

script:
  - go test -v ./server/jam-server
  - pushd server/log-interceptor; ./test.sh; popd
